### PR TITLE
release: v1.0.0b3

### PR DESCRIPTION
**Pull request by lnielsen**
@tiborsimko This should fix the bad wheel package on pypi (v1.0.0b2) 

Signed-off-by: Lars Holm Nielsen <lars.holm.nielsen@cern.ch>

### CODE REVIEW

**Comment by tiborsimko** [comment]
I guess we'll wait for the release of `requirements-builder`? https://github.com/inveniosoftware/requirements-builder/pull/28

**Comment by lnielsen** [comment]
Ups, sorry didn't see your message before I merged. It should be fine without requirements-builder. I think this was mainly in Invenio-OAIServer it caused problems.

**Comment by tiborsimko** [comment]
Thanks, for me yesterday it was actually `invenio-accounts` that coused troubles:

```
Collecting ipaddr>=2.1.11 (from invenio-accounts<1.1.0,>=1.0.0b1->invenio==3.0.0a5.dev20161219)
  Downloading ipaddr-2.1.11.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-efgahelb/ipaddr/setup.py", line 19, in <module>
        import ipaddr
      File "/tmp/pip-build-efgahelb/ipaddr/ipaddr.py", line 1450
        ip_int = 0L
                  ^
    SyntaxError: invalid syntax
```

**Comment by lnielsen** [comment]
Yes, the invenio-accounts wheel package was broken yesterday. What I meant was that merging this PR was fine since without the req builder while OAIServer will not build correctly without the new req builder.

v1.0.0b3 is on pypi now so should work

**Pull request merged**
