### PR TITLE
cli: changed commands to flat structure

### LINKED ISSUE #29: cli: change to flat structure
Change CLI to flat structure:

from:

```
inveniomanage accounts users create
inveniomanage accounts users activate
inveniomanage accounts users deactivate
inveniomanage accounts roles add
inveniomanage accounts roles create
inveniomanage accounts roles remove
```

to 

```
inveniomanage accounts createuser
inveniomanage accounts activateuser
inveniomanage accounts deactivateuser
inveniomanage accounts addrole
inveniomanage accounts createrole
inveniomanage accounts removerole
```

### PR DESCRIPTION
**Pull request by JavierDelgadoFernandez**
* The commands of CLI tool have been changed to use
  just a keyword instead of the two keywords used before.
  (Closes #29)

Signed-off-by: Javier Delgado <javier.delgado.fernandez@cern.ch>

### CODE REVIEW

**Comment by lnielsen** [comment]
There's some documentation missing to be updated in https://github.com/inveniosoftware/invenio-accounts/blob/next/examples/app.py

Can you do a git grep for ``accounts users`` and ``accounts roles`` and see if there's any left overs.

**Comment by JavierDelgadoFernandez** [comment]
@lnielsen Done. I have checked with ```git grep``` and everything is ok now.

**Comment by lnielsen** [comment]
Great thanks. 

(Just for the record) Discussed in stand up - changed naming scheme from creatuser to usercreate

**Comment by lnielsen** [comment]
Please rebase on top of next

**Comment by JavierDelgadoFernandez** [comment]
@lnielsen Done.

**Comment by lnielsen** [comment]
@JavierDelgadoFernandez I think something went wrong with the rebasing ….the SHA of global: fix ACCOUNTS_USE_CELERY behaviour is different than the one in next.

**Comment by JavierDelgadoFernandez** [comment]
@lnielsen Maybe it was because  I changed the order of the commits, I have recommitted with the original order.

**Comment by lnielsen** [comment]
Merging via #31

**Pull request closed without merging**
